### ISSUE TITLE
http://localhost:9100/index.html is redirecting to ./ - this break the auth flow

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/ocis-phoenix#38]
![Screenshot from 2020-02-04 16-27-40](https://user-images.githubusercontent.com/1005065/73758753-53ba1c00-476b-11ea-97ce-5ac5f25b7259.png)

We should simply serve the index.html ...

**Comment by DeepDiver1975** [comment]
this redirect is discarding query parameters as needed by the open id connect flow.

**Comment by DeepDiver1975** [comment]
Expected behaviour - https://golang.org/pkg/net/http/#FileServer

**Comment by DeepDiver1975** [comment]
in the code base: https://github.com/golang/go/blob/b8d339bc8dbb0754d1b6aa8a748598907e5b2dd2/src/net/http/fs.go#L549

**Comment by butonic** [comment]
hm ... can we take `index.html` out of the url?

if not, we could add a middleware that cuts it out of the path so the static middleware handles it properly.

**Comment by DeepDiver1975** [comment]
I already did some research in this. On it With Alex
