### ISSUE TITLE
Files action menu not available

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis-phoenix#51]
When using the current master version of phonenix with ocis, we dont get the files action menu.
Starting ocis-phoenix with `PHOENIX_ASSET_PATH=/path/to/phoenix/dist`

![sr](https://user-images.githubusercontent.com/19869344/75843947-b818db80-5dfc-11ea-87f9-525ac377cbc7.gif)

**Comment by PVince81** [comment]
I can confirm this.

I managed to scroll down somehow and it seems that the menu is rendered below the file list container. The reason why is currently mysterious. There are no errors related to any CSS or styles that might not have been initialized properly.

Needs further research.

**Comment by PVince81** [comment]
Comparing computed styles:

### OCIS Phoenix
<img width="906" alt="image" src="https://user-images.githubusercontent.com/277525/77186309-f5ef5280-6ad2-11ea-9f5e-f1168af7dd0b.png">


### Phoenix demo server (OC 10 backend)
<img width="928" alt="image" src="https://user-images.githubusercontent.com/277525/77186329-00115100-6ad3-11ea-852b-db7955cd5236.png">


From what I see, in the latter case where it works **something** has properly set the absolute position using inline styles for "top" and "left". But on OCIS it didn't happen.

One could think that maybe UIKit didn't initialize properly, but if it didn't then the dropdown wouldn't open at all.

**Comment by PVince81** [comment]
Hmmm in OCIS the uk-drop markup also looks doubled.
Wondering if something has initialized twice ?!

**Comment by PVince81** [comment]
ohhh... the fileid is a long string in OCIS, so it cannot be used in places like element id. This is likely it!

**Comment by PVince81** [comment]
I've raised https://github.com/owncloud/phoenix/issues/3214 to look into this issue in a broader scope.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/phoenix/pull/3248

@dpakach not sure if you'll want to reenable some tests there ? if yes, feel free to push there
